### PR TITLE
Export footer to code using teleportHQ

### LINKED ISSUE #323: Upgrade footer to UI v3

### PR DESCRIPTION
**Pull request by rrchai**
- Fixes #323

### CODE REVIEW

**Comment by tschaffter** [comment]
@rrchai @vpchung we can use this branch to import the footer

**Comment by vpchung** [comment]
> @rrchai
[change readme back](https://github.com/Sage-Bionetworks/challenge-registry/pull/174/commits/fb40de6cea7c63ae5286245e242ffb75f1878d23)

Aww, I liked the beer emoji in the README...... (😆)

**Comment by rrchai** [comment]
@vpchung It is still in the README~  Let's keep it 🍻

**Comment by tschaffter** [comment]
## TODO

- [ ] Resolve conflicts (@rrchai )
- [ ] Take a pass on this PR / clean up code (@rrchai )
- [ ] Take final pass on this PR / identify where reusable code should be placed (@vpchung )

**Comment by tschaffter** [comment]
@vpchung It may be easier to start a new PR from `main` and copy-paste footer-related code rather than solving the conflicts. This PR also brings changes to the README that are no longer relevant.

**Comment by rrchai** [comment]
The conflicts are fixed

**Comment by tschaffter** [comment]
I received a notification from GH a few days ago asking me to review this PR. I don't see in this PR discussion someone assigning me to that task recently. Do you want me to review it? @vpchung

**Comment by tschaffter** [comment]
Change the ticket that this PR addresses to #323.

**Comment by rrchai** [comment]
move to #350

**Pull request closed without merging**
