### PR TITLE
feat(ui): Add team page to app

### PR DESCRIPTION
**Pull request by vpchung**
Addresses #355

### CODE REVIEW

**Comment by vpchung** [comment]
This PR will also play a part in writing the docs on how to export Figma-to-code (#197) and how to add a new library/component to the app.

**Comment by tschaffter** [comment]
@vpchung See #415

**Comment by tschaffter** [comment]
@vpchung 

This branch has been updated with the latest content from `main`. After checking it out, you will need to rebuild your devcontainer because of a recent change to it.

**Comment by tschaffter** [comment]
@vpchung This branch is now up to date with `main`. After starting the app, I can successfully access the placeholder team page you created. Note that `main` and this feature branch now use Yarn 2+. Next time you pull from the upstream `main` or this branch, you then need to remove your `node_modules` folder and run `challenge-install` to install the npm dependencies with Yarn 2+.

**Pull request closed without merging**
