### PR TITLE
feat(ui): team page

### PR DESCRIPTION
**Pull request by vpchung**
Accomplishes #355 :

Screen Shot 2022-10-14 at 2 52 24 AM

### CODE REVIEW

**Comment by vpchung** [comment]
Added two members:

updated

**Review by tschaffter — APPROVED** [review]
Looks nice! Here are two updates:

- Capitalize roles
- Set the role of Amy to "Program Manager"

**Comment by vpchung** [comment]
@tschaffter noooo, not the capitalizationnnnnnn

Jk :slightly_smiling_face: Will do.

**Comment by vpchung** [comment]
updated_roles

**Comment by tschaffter** [comment]
@vpchung Please set my role(s) to "Project lead, Architect and Lead developer"

**Pull request merged**
