### PR TITLE
Update navbar to UI v3

### PR DESCRIPTION
**Pull request by vpchung**
This PR includes the themes for the navbar component.

TODO: 
- [x] add theming for when the user is logged in.

### CODE REVIEW

**Comment by tschaffter** [comment]
> add theming for when the user is logged in.

Is this task complete?

**Comment by vpchung** [comment]
> Has this task been completed?
Not yet - I hope to get around to it tomorrow.

> Same comment as in https://github.com/Sage-Bionetworks/challenge-registry/pull/354. This should not be a problem if we merge the footer PR first.
Yes, apologies for that! I mentioned in an [earlier commen](https://github.com/Sage-Bionetworks/challenge-registry/pull/353#issuecomment-1162159589)t that this PR will include updates for the footer component.

**Comment by vpchung** [comment]
Design added for when user is logged in:
Screen Shot 2022-06-24 at 12 10 39 AM

P.S. for some reason, the listed items aren't reflecting the changes made to `mock-menu-items.ts` (hence why "Log out" is showing up twice)

**Comment by rrchai** [comment]
> for some reason, the listed items aren't reflecting the changes made to mock-menu-items.ts (hence why "Log out" is showing up twice) 

This has been fixed in [98afa5](https://github.com/Sage-Bionetworks/challenge-registry/pull/353/commits/98afa5ad4eae84e6383635b788eeec089d025d71).

Recording 2022-06-24 at 17 11 19

Now, clicking 'Profile' will redirect to the user-profile using mock data - [683aabe](https://github.com/Sage-Bionetworks/challenge-registry/pull/353/commits/683aabee118cb020c556877a1021e21c892c3403)

**Comment by rrchai** [comment]
@tschaffter It is ready to review for merging.

**Pull request merged**
