### PR TITLE
chore: Upgrade to Yarn 3

### LINKED ISSUE #586: Evaluate not removing `node_modules` after `git merge`
The article [Safer Node.js coding with git hooks and husky](https://ivantanev.com/safer-coding-with-husky-hooks/) suggest to remove `node_modules` and do a fresh install of Node.js dependencies after merging a branch. This operation is time consuming and in #580 I decided to skip this step.

I contacted the author of the article for more info and he replied the following:

> With post-merge, we're doing a full reinstall of all node modules by first deleting them, because I have seen yarn 1.x often break when deep transitive dependencies change during a merge specifically. I don't know why this happens, exactly. It is also valid to omit this hook, and let developers run "yarn install" manually.

A few weeks ago I tried to skip removing `node_modules` after merge but encountered an issue: I think that the command `yarn` or `nx` was not longer available? I was in the middle of another task so I reverted back.

The goal of this ticket is to try to briefly reproduce the error I encountered or any error that may result from no longer removing `node_modules` after merge. Upgrading to Yarn 3 or pnpm is also considered but as a parallel solution.

### LINKED ISSUE #588: Explore `pnpm` and `yarn v3`
Yarn v1 is in maintenance mode since 2020. `yarn v3` and `pnpm` are the most promising candidates to replace `yarn v1`. They should also provide a solution to the need (?) to remove `node_modules` after a git merge.

> **Node**
> Yarn v1 is still extensively used because v2 introduced many broken changes, which lead to a controversy. Not sure about the state of v3.

### PR DESCRIPTION
**Pull request by tschaffter**
- Fixes #588
- Fixes #586

## Notes

- This PR upgrades the development environment to Yarn 2+ ("Yarn Berry").
- Yarn 2+ introduces lock file format v2.
  - Look similar to v1 but best to regenerate the lock file with Yarn 2+ if possible.
- [Motivations and performance benchmarks](https://docs.google.com/presentation/d/18UR44fXblQ7WEg0Sc39lPrXHdWDDxmJgkU3Qi7t9qoY/edit#slide=id.gfe41b02ef2_0_304)
- Yarn 3 CLI is almost identical to Yarn 1 CLI.
  - The only difference relevant to our project is:
    - `yarn install --frozen-lockfile` is replaced by `yarn install --immutable`
    - `yarn bin` is not longer displaying the path to the local `node_modules/.bin` folder (used in `dev-env.sh`).

## Testing

1. Checkout this branch.
2. Rebuild the dev container.
3. Remove the existing `node_modules`.
4. Install the Node.js dependencies: `challenge-install`.
5. Start the challenge registry: `nx serve challenge-registry`.
6. Check that the registry loads successfully in the browser. 

> **Note**
>Repeat Steps 3-4 when returning to a branch that uses Yarn 1.

## TODO before merging

- [ ] Replace dev container image tag by whatever value is used in `main`.

### CODE REVIEW

**Comment by tschaffter** [comment]
## Yarn messes up with $PATH

```console
$ echo $PATH
/vscode/vscode-server/bin/linux-x64/e4503b30fc78200f846c62cf8091b76ff5547662/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:➤ YN0000: ng ➤ YN0000: nx-cloud ➤ YN0000: openapi-generator-cli ➤ YN0000: openapi ➤ YN0000: coveralls ➤ YN0000: cypress ➤ YN0000: eslint ➤ YN0000: hint ➤ YN0000: husky ➤ YN0000: lint-openapi ➤ YN0000: prettier ➤ YN0000: redoc-cli ➤ YN0000: shx ➤ YN0000: tsc ➤ YN0000: tsserver ➤ YN0000: ng-xi18n ➤ YN0000: ngc ➤ YN0000: ngcc ➤ YN0000: eslint-config-prettier ➤ YN0000: jest ➤ YN0000: ng-packagr ➤ YN0000: nx ➤ YN0000: ts-jest ➤ YN0000: ts-node ➤ YN0000: ts-node-cwd ➤ YN0000: ts-node-esm ➤ YN0000: ts-node-script ➤ YN0000: ts-node-transpile-only ➤ YN0000: ts-script ➤ YN0000: Done in 0s 55ms
```

**Comment by tschaffter** [comment]
@rrchai Would you have time to review this PR before our next dev workshop (September 2nd)?

**Comment by tschaffter** [comment]
@rrchai This PR can be tested despite the conflict with `yarn.lock` shown above. The lock file that comes with this PR (generated with Yarn 3) is different from the lock file in `main` (generated with Yarn 1).

**Review by rrchai — APPROVED** [review]
Thanks for upgrading `yarn`. I like the colors here during the `challenge-install`:

Screen Shot 2022-09-01 at 9 59 43 PM

I can reproduce similar running time for installation with `yarn 2+` - faster is always great 🍾  :
```console
hyperfine  --warmup 1 --prepare 'rm -rf node_modules' --runs 5 'yarn install --immutable'
Benchmark 1: yarn install --immutable
  Time (mean ± σ):     55.868 s ±  0.637 s    [User: 71.734 s, System: 37.474 s]
  Range (min … max):   54.812 s … 56.484 s    5 runs
```

And I can access to the webpage with no errors.

**Pull request merged**
